server:
  #端口
  port: 8080
spring:
  #应用名称
  application:
    name: Java-RenHang
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: omy360
    url: jdbc:mysql://192.168.1.80:3306/renhang?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useUnicode=true
    type: com.alibaba.druid.pool.DruidDataSource
  #去求超时时间
  mvc:
    async:
      request-timeout: 60000
#mybatisXML包扫描
mybatis:
  mapperLocations: classpath:com/renhang/core/*/*/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#闲玩配置参数;
XWAndroid:
  appid: 4757
  appsecret: zmfr6t6myz7h9akz
XWIOS:
  appId: 4777
  appsecret: n14fqd8h5afbqsy3
#闲玩任务配置参数;
XWAndroidTask:
  appid: 3702
  appsecret: 1m5xs87lhouzunle
XWIOSTask:
  appId:
  appsecret:
#任务墙入口配置参数;
TaskEntry:
  name: QMUe
  secret: bkmm00362
#闲娱参数
XYWeb:
  id: 458
  appKey: bc62175cb7f4d4a1ab
#小桔参数
origin:
  appKey: xiongtest
  appSecret: HlqAnnonTUxDr51AynjlNYzdt+OYXaqceMI70CskDis=
  dataSecret: HlqAnnonTUxDr51A
  sigSecret: XaqceMI70CskDis=
#肯德基
kfc:
  id: 10247
  secret: ryw81wbh5k673i05
  url: https://live-test.qianzhu8.com
#携程
xiecheng:
  AID: 1245771
  SID: 3004697
  KEY: 112233
