package com.renhang.core.callback.xiecheng.pojo;

public enum OrderStatus {

    DIY_CONFIRMING("自游行我携状态-确认中"),
    DIY_CONFIRMED("自游行我携状态-已确认"),
    DIY_PAYED("自游行我携状态-已付款"),
    DIY_COMPLETED("自游行我携状态-已成交"),
    DIY_CANCELLED("自游行我携状态-已取消"),
    DIY_UNSUBCRIBE_ALL(" 自游行我携状态-全部退订"),
    DIY_UNSUBCRIBE_PART(" 自游行我携状态-部分退订"),
    DIY_PAYED_PART("自游行我携状态-部分付款"),
    DIY_UNCOMMIT("自游行我携状态-未提交"),
    DIY_UNPAID("自游行我携状态-待支付"),
    DIY_CONFIRMING_NEW("自游行我携状态-确认中"),
    PIAO_UNCOMMIT("门票我携状态-已提交"),
    PIAO_CONFIRMING("门票我携状态-确认中"),
    PIAO_CONFIRMED("门票我携状态-已确认"),
    PIAO_PAYING(" 门票我携状态-待付款"),
    PIAO_PAYED("门票我携状态-已付款"),
    PIAO_UNSUBSCRIBED_ALL("门票我携状态-退订"),
    PIAO_COMPLETED("门票我携状态-成交"),
    PIAO_CANCELLED(" 门票我携状态-取消"),
    PIAO_CANCELLING(" 门票我携状态-取消中"),
    PIAO_UNSUBSCRIBING("门票我携状态-退订中"),
    PIAO_PAYED_PROCESSING(" 门票我携状态-支付处理中"),
    PIAO_PAY_FAILED("门票我携状态-支付失败"),
    VACATION_UNCOMMIT("团队游我携状态-未提交"),
    VACATION_COMMITTED("团队游我携状态-已提交"),
    VACATION_CONFIRMING(" 团队游我携状态-确认中"),
    VACATION_CONFIRMED("团队游我携状态-已确认"),
    VACATION_PAYED("团队游我携状态-已付款"),
    VACATION_TICKET("团队游我携状态-已出票"),
    VACATION_COMPLETED("团队游我携状态-已成交"),
    VACATION_UNSUBCRIBE_ALL("团队游我携状态-全部退订"),
    VACATION_UNSUBCRIBE_PART("团队游我携状态-部分退订"),
    VACATION_CANCELLED("团队游我携状态-已取消"),
    VACATION_TOPAY("团队游我携状态-待支付"),
    TRANS_TOPAY("火车票我携状态-待支付"),
    TRANS_PAY_CONFIRMING("火车票我携状态-支付处理中"),
    TRANS_PAYED_FAILURE("火车票我携状态-支付失败"),
    TRANS_TO_BUY(" 火车票我携状态-支付成功待出票"),
    TRANS_BUYING("火车票我携状态-购票中"),
    TRANS_BOUGHT("火车票我携状态-已购票"),
    TRANS_DELIVERED("火车票我携状态-已配送"),
    TRANS_COMPLETED("火车票我携状态-已成交"),
    TRANS_CANCELLED(" 火车票我携状态-已取消"),
    TRANS_UNSUBCRIBE_PART("火车票我携状态-部分退票"),
    TRANS_UNSUBCRIBE_ALL(" 火车票我携状态-全部退票"),
    TRANS_BUY_FAILURE("火车票我携状态-购票失败"),
    CAR_COMMITTED("用车我携状态-已提交"),
    CAR_PROCESSING("用车我携状态-处理中"),
    CAR_CONFIRMED("用车我携状态-已确认"),
    CAR_CANCELLING("用车我携状态-取消中"),
    CAR_CANCELLED("用车我携状态-已取消"),
    CAR_COMPLETED(" 用车我携状态-已成交"),
    CAR_WAITING_PAY("用车我携状态-待支付"),
    CAR_MODIFYING("用车我携状态-修改中"),
    ACTIVITY_COMMITTED("当地活动我携状态-已提交"),
    ACTIVITY_WAIT_PAY("当地活动我携状态-待付款"),
    ACTIVITY_PAYED("当地活动我携状态-已付款"),
    ACTIVITY_CONFIRMING("当地活动我携状态-确认中"),
    ACTIVITY_CONFIRMED("当地活动我携状态-已确认"),
    ACTIVITY_DEALT("当地活动我携状态-已成交"),
    ACTIVITY_UNSUBSCRIBING("当地活动我携状态-退订中"),
    ACTIVITY_UNSUBSCRIBED("当地活动我携状态-已退订"),
    ACTIVITY_CANCELLING("当地活动我携状态-取消中"),
    ACTIVITY_CANCELLED("当地活动我携状态-已取消"),
    ACTIVITY_DEALT_PART("当地活动我携状态-成交部分退订"),
    ACTIVITY_PAYED_PROCESSING(" 当地活动我携状态-支付处理中"),
    ACTIVITY_PAY_FAILED("当地活动我携状态-支付失败"),
    BUS_TOPAY(" 汽车票我携状态-待支付"),
    BUS_PAYING("汽车票我携状态-支付处理中"),
    BUS_PAY_FAILED("汽车票我携状态-支付失败"),
    BUS_TOTICKET("汽车票我携状态-等待购票"),
    BUS_TICKETING(" 汽车票我携状态-购票中"),
    BUS_DEALT("汽车票我携状态-已成交（出票成功, 后续废弃, 拆分成 BUS_DEALT_NEW,BUS_UNSUBSCRIBE_PART, BUS_UNSUBSCRIBE）"),
    BUS_REFUNDING("汽车票我携状态-退款中"),
    BUS_REFUND_ALL(" 汽车票我携状态-全部退款"),
    BUS_CANCELLED("汽车票我携状态-已取消"),
    BUS_DEALT_NEW("汽车票我携状态-已成交(新)"),
    BUS_UNSUBSCRIBE_PART(" 汽车票我携状态-部分退票(新) "),
    BUS_UNSUBSCRIBE("汽车票我携状态-成功退票(新)"),
    SCENERYHOTEL_CONFIRMING("景酒我携状态-确认中"),
    SCENERYHOTEL_CONFIRMED("景酒我携状态-已确认"),
    SCENERYHOTEL_PAYED("景酒我携状态-已付款(后续废弃) "),
    SCENERYHOTEL_COMPLETED("景酒我携状态-已成交"),
    SCENERYHOTEL_CANCELLED("景酒我携状态-已取消"),
    SCENERYHOTEL_UNSUBCRIBE_ALL("景酒我携状态-全部退订(后续废弃, 请用已退订) "),
    SCENERYHOTEL_UNSUBCRIBE_PART("景酒我携状态-部分退订(后续废弃, 请用已退订)"),
    SCENERYHOTEL_PAYED_PART("景酒我携状态-部分付款(后续废弃)"),
    SCENERYHOTEL_TOPAY("景酒我携状态-待付款 "),
    SCENERYHOTEL_UNSUBCRIBE("景酒我携状态-已退订"),
    CRUISE_UNCOMMIT(" 邮轮我携状态-未提交"),
    CRUISE_COMMITTED("邮轮我携状态-已提交"),
    CRUISE_CONFIRMING("邮轮我携状态-确认中"),
    CRUISE_CONFIRMED("邮轮我携状态-已确认"),
    CRUISE_PAYED("邮轮我携状态-已付款"),
    CRUISE_TICKET("邮轮我携状态-已出票"),
    CRUISE_COMPLETED(" 邮轮我携状态-已成交"),
    CRUISE_UNSUBCRIBE_ALL("邮轮我携状态-全部退订"),
    CRUISE_UNSUBCRIBE_PART("邮轮我携状态-部分退订"),
    CRUISE_CANCELLED("邮轮我携状态-已取消"),
    CRUISE_TOPAY("邮轮我携状态-待支付"),
    CRUISE_CABIN_UNCONFIRMED(" 邮轮我携状态-舱房待确认"),
    CRUISE_UNTRAVEL("邮轮我携状态-待出行");

    private String chinese;

    OrderStatus(String chinese) {
        this.chinese = chinese;
    }

    public String getChinese() {
        return chinese;
    }

}
